### ISSUE TITLE
[cart] add query connection when confirm button clicked

### ISSUE THREAD

**Issue by Jaeja-Phil** [Jaeja-Phil/cal-culator-mobile-client#42]
### Job Description:

- [ ] use mutation query to add the items in the cart

### Todo:

- [ ] UI component

- [ ] UX component (clicking and enabling selects)

- [ ] mutation query && server connection

### Estimated:

- [ ] 7 hrs
