### ISSUE TITLE
[feature] add/fix_config page

### ISSUE THREAD

**Issue by Kyung-Douhyun** [Jaeja-Phil/cal-culator-mobile-client#50]
### Job Description:

- [ ] 설정 페이지 수정 및 기능 추가

### Todo:

- [ ] 유저 정보 실기간 동기화
- [ ] 유저 정보 수정 기능
- [ ] UI

### Estimated:

- [ ] 1~3 hrs
